name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a compatible Node.js version

      # Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install | bash
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # Authenticate Railway CLI
      - name: Authenticate Railway CLI
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway login --token $RAILWAY_API_TOKEN

      # Deploy to Railway
      - name: Deploy Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway up --project-id ${{ secrets.RAILWAY_PROJECT_ID }}

