name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Navigate to Frontend
        run: |
          if [ -d "./frontend" ]; then
            cd frontend
          else
            echo "Error: frontend directory not found"
            exit 1
          fi

      - name: Install Vue CLI Locally
        run: npx vue --version || npm install -g @vue/cli

      - name: Install Dependencies
        run: npm ci

      - name: Audit and Fix Vulnerabilities
        run: |
          npm audit fix
          npm audit fix --force

      - name: Build Frontend
        run: npx vue-cli-service build
