name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a Node.js version compatible with your project

      # Step 3: Install Railway CLI using npm
      - name: Install Railway CLI
        run: |
          npm install -g railway

      # Step 4: Authenticate Railway CLI
      - name: Authenticate Railway CLI
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway login --token $RAILWAY_API_TOKEN

      # Step 5: Deploy to Railway
      - name: Deploy Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway up --project-id ${{ secrets.RAILWAY_PROJECT_ID }}
