name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:

jobs:
  build-and-deploy:
    name: Build and Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the Node.js version

      # Install and build the frontend
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Install and build the backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install

      # Deploy to Railway
      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment: production  # Change to your Railway environment name if needed
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

