name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 4. Set NODE_ENV to production
      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # 5. Install FTP utilities
      - name: Install FTP utilities
        run: sudo apt-get install lftp

      # 6. Configure environment variables
      - name: Configure database and server environment variables
        run: |
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}" >> $GITHUB_ENV
          echo "SERVER_PASSWORD=${{ secrets.SERVER_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      # 7. Configure API URL for production
      - name: Configure API URL
        run: |
          echo "VUE_APP_API_URL=https://your-backend-url/api" >> frontend/.env.production

      # 8. Build the frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # 9. Move frontend build to backend's public folder
      - name: Move frontend to backend
        run: |
          cp -r frontend/dist/* backend/public/

      # 10. Deploy backend to FTP server
      - name: Deploy backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: backend
          server-dir: /public_html/backend

      # 11. Test deployment
      - name: Test Deployment
        run: |
          echo "Deployment complete. Please verify the site is live."
