name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code with commit history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Run Commitlint
      - name: Run Commitlint
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            npx commitlint --from=HEAD~1 --to=HEAD;
          else
            echo "Skipping commitlint as there is no previous commit.";
          fi
